export const numbers = [
    { text: "9" },
    { text: "8" },
    { text: "7" },
    { text: "6" },
    { text: "5" },
    { text: "4" },
    { text: "3" },
    { text: "2" },
    { text: "1" },
    { text: "0" },
    { text: "0" },
    { text: "0" },
    { text: "0" },
    { text: "0" },
    { text: "0" },
    { text: "0" },
]